// ============================================================
// FILE: backend/scripts/seedSpecies.js
//
// COMPLETE RE-SEED:
// - All 18 species now have real imageUrl (Wikipedia Commons)
// - Added habitat, threats, funFacts for rich detail pages
// - Added real coordinates for Indian zones
// - conservationStatus normalized to match app enum
// ============================================================

const mongoose = require("mongoose");
const dotenv   = require("dotenv");
dotenv.config();
mongoose.set("strictQuery", false);

const Species = require("../models/Species");

// ─── Wikipedia Commons image URLs (stable, no API key required) ──────────────
const speciesData = [
  {
    name:               "Bengal Tiger",
    scientificName:     "Panthera tigris tigris",
    type:               "Mammal",
    zone:               "Indo-Gangetic Plain",
    ecosystem:          "Tropical Forest",
    population:         2967,
    habitatLoss:        70,
    pollutionLevel:     40,
    climateRisk:        55,
    conservationStatus: "Endangered",
    description:        "The Bengal Tiger is India's national animal and the most numerous tiger subspecies in the world. Found primarily in the Sundarbans delta and reserves across central India, it is an apex predator that plays a crucial role in maintaining the ecological balance of its habitat.",
    habitat:            "Dense tropical and subtropical moist broadleaf forests, grasslands, and mangrove swamps",
    threats:            ["Poaching for skin and bones", "Habitat destruction and fragmentation", "Human-wildlife conflict", "Prey depletion"],
    funFacts:           ["No two tigers have the same stripe pattern — like human fingerprints", "Tigers are strong swimmers and often cool off in streams", "A group of tigers is called an ambush or a streak", "Bengal tigers can leap up to 10 metres in a single bound"],
    coordinates:        { lat: 21.9, lng: 82.5, locationName: "Central India Tiger Reserves" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/1/17/Tiger_in_Ranthambhore.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/1/17/Tiger_in_Ranthambhore.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/5/56/Tiger.50.jpg",
    ],
  },
  {
    name:               "Indian Elephant",
    scientificName:     "Elephas maximus indicus",
    type:               "Mammal",
    zone:               "Western Ghats",
    ecosystem:          "Tropical Forest",
    population:         27312,
    habitatLoss:        65,
    pollutionLevel:     30,
    climateRisk:        45,
    conservationStatus: "Endangered",
    description:        "The Indian Elephant is the largest land animal in Asia. Known for exceptional intelligence and strong social bonds, these magnificent creatures are found in forests across India. They are keystone species — essential for seed dispersal and maintaining forest structure.",
    habitat:            "Tropical and subtropical moist broadleaf forests, scrub forests, and grasslands",
    threats:            ["Habitat loss due to agriculture encroachment", "Human-elephant conflict", "Illegal ivory poaching", "Railway track fatalities"],
    funFacts:           ["Elephants can recognize themselves in a mirror — a sign of self-awareness", "An elephant's trunk has over 40,000 muscles", "Elephants mourn their dead and have 'funeral rituals'", "They communicate using infrasound that humans cannot hear"],
    coordinates:        { lat: 11.3, lng: 76.8, locationName: "Nilgiri Biosphere Reserve" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/3/37/African_Bush_Elephant.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/3/37/African_Bush_Elephant.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/b/be/Asian_Elephant_2_%28PSF%29.jpg",
    ],
  },
  {
    name:               "Snow Leopard",
    scientificName:     "Panthera uncia",
    type:               "Mammal",
    zone:               "Himalayan",
    ecosystem:          "Alpine Meadow",
    population:         4500,
    habitatLoss:        60,
    pollutionLevel:     20,
    climateRisk:        80,
    conservationStatus: "Vulnerable",
    description:        "The Snow Leopard is the ghost of the mountains — elusive and rarely seen. This magnificent cat rules the high-altitude terrain of the Himalayas in India. Its thick, patterned fur provides camouflage in the rocky, snow-covered landscape.",
    habitat:            "Alpine and subalpine zones, rocky terrain, and cliffs at 3,000–5,500 m elevation",
    threats:            ["Climate change shrinking prey habitat", "Poaching for fur and bones", "Retaliatory killing by herders", "Declining prey populations"],
    funFacts:           ["Snow leopards cannot roar — they make a puffing 'chuff' sound", "Their long, thick tail acts as a balance and a scarf to wrap around their face", "A snow leopard can kill prey 3 times its own size", "They are called the 'ghosts of the mountains' for their elusiveness"],
    coordinates:        { lat: 32.5, lng: 77.0, locationName: "Spiti Valley, Himachal Pradesh" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/b/b3/Snow_leopard_%28Uncia_uncia%29_2.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/b/b3/Snow_leopard_%28Uncia_uncia%29_2.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/3/3c/Las_Vegas_Snow_Leopard.jpg",
    ],
  },
  {
    name:               "Indian Peafowl",
    scientificName:     "Pavo cristatus",
    type:               "Bird",
    zone:               "Deccan Plateau",
    ecosystem:          "Grassland",
    population:         100000,
    habitatLoss:        20,
    pollutionLevel:     15,
    climateRisk:        25,
    conservationStatus: "Safe",
    description:        "The Indian Peafowl is India's national bird, known for its spectacular iridescent plumage and elaborate courtship dance. The peacock's train is not actually its tail but elongated upper tail coverts. This striking bird is found across the Indian subcontinent.",
    habitat:            "Open forests, grasslands, agricultural fields, and near human settlements",
    threats:            ["Habitat loss", "Illegal hunting for feathers", "Road accidents", "Pesticide poisoning"],
    funFacts:           ["The peacock's train can be up to 1.8 metres long — 60% of its total length", "Peahens are believed to choose mates based on the quality of their train display", "Peacocks can fly short distances despite their heavy plumage", "Their loud call is often used as a natural alarm for approaching predators"],
    coordinates:        { lat: 17.5, lng: 78.5, locationName: "Deccan Plateau" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/1/1e/Peacock_Plumage.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/1/1e/Peacock_Plumage.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/a/a5/Peacock_India.jpg",
    ],
  },
  {
    name:               "Asiatic Lion",
    scientificName:     "Panthera leo persica",
    type:               "Mammal",
    zone:               "Gir Forest",
    ecosystem:          "Dry Forest",
    population:         674,
    habitatLoss:        50,
    pollutionLevel:     20,
    climateRisk:        40,
    conservationStatus: "Endangered",
    description:        "The Asiatic Lion exists only in one place on Earth — the Gir Forest of Gujarat, India. Slightly smaller than African lions, they have a distinctive fold of skin on their belly and a less developed mane. A remarkable conservation success story with population rising from just 20 in 1900.",
    habitat:            "Dry deciduous forests and scrublands of Gir National Park, Gujarat",
    threats:            ["Extremely limited habitat range", "Disease outbreak risk", "Highway and railway accidents", "Human-lion conflict"],
    funFacts:           ["Asiatic lions live in smaller prides than African lions, often with males and females in separate groups", "The Gir lion population has grown from 20 to over 674 since 1900", "They can consume 25 kg of meat in a single meal", "Asiatic lions are the only lions with a fold of skin along their abdomen"],
    coordinates:        { lat: 21.1, lng: 70.8, locationName: "Gir National Park, Gujarat" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/7/73/Lion_waiting_in_Namibia.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/7/73/Lion_waiting_in_Namibia.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/f/f8/Asiatic_Lion_in_Gir_forest.jpg",
    ],
  },
  {
    name:               "Red Panda",
    scientificName:     "Ailurus fulgens",
    type:               "Mammal",
    zone:               "Eastern Himalayas",
    ecosystem:          "Mountain Forest",
    population:         10000,
    habitatLoss:        60,
    pollutionLevel:     25,
    climateRisk:        50,
    conservationStatus: "Endangered",
    description:        "The Red Panda is a small arboreal mammal native to the eastern Himalayas. Despite its name, it is not closely related to the Giant Panda. With its rusty red fur, bushy tail, and raccoon-like face, the Red Panda is one of the most charming animals in the Himalayan forests.",
    habitat:            "Temperate forests with dense bamboo undergrowth at 2,200–4,800 m elevation",
    threats:            ["Deforestation and habitat fragmentation", "Poaching and illegal pet trade", "Climate change affecting bamboo availability", "Inbreeding in small isolated populations"],
    funFacts:           ["Red pandas spend about 13 hours a day foraging for food — mostly bamboo", "They have a false thumb (extended wrist bone) to grip bamboo like giant pandas", "Red pandas are the original 'Firefox' — Mozilla's browser logo is based on them", "They use their long, bushy tails as blankets in cold weather"],
    coordinates:        { lat: 27.0, lng: 88.5, locationName: "Singalila National Park, Sikkim" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/b/b2/Ailurus_fulgens_-National_Zoo-8a.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/b/b2/Ailurus_fulgens_-National_Zoo-8a.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/5/50/RedPandaFullBody.JPG",
    ],
  },
  {
    name:               "Blackbuck",
    scientificName:     "Antilope cervicapra",
    type:               "Mammal",
    zone:               "Central India",
    ecosystem:          "Grassland",
    population:         50000,
    habitatLoss:        30,
    pollutionLevel:     10,
    climateRisk:        20,
    conservationStatus: "Safe",
    description:        "The Blackbuck is one of the fastest animals in India, capable of reaching speeds of 80 km/h. The males have magnificent spiralling horns and a striking two-tone coat, while females are tan-coloured. Once numbering in the millions, hunting and habitat loss reduced their numbers drastically.",
    habitat:            "Open plains, grasslands, and lightly wooded areas",
    threats:            ["Habitat conversion to agriculture", "Hunting and poaching", "Vehicle collisions", "Disease from domestic livestock"],
    funFacts:           ["Blackbucks can run at 80 km/h — among the fastest land animals", "Only male blackbucks grow horns, which can be up to 79 cm long", "Male blackbucks turn darker with age — young males are brown, old males are black", "They are sacred to the Bishnoi community of Rajasthan, who protect them fiercely"],
    coordinates:        { lat: 21.0, lng: 75.0, locationName: "Vel National Park, Gujarat" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/7/72/Blackbuck_male.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/7/72/Blackbuck_male.jpg",
    ],
  },
  {
    name:               "Nilgai",
    scientificName:     "Boselaphus tragocamelus",
    type:               "Mammal",
    zone:               "Northern India",
    ecosystem:          "Grassland",
    population:         200000,
    habitatLoss:        25,
    pollutionLevel:     10,
    climateRisk:        20,
    conservationStatus: "Safe",
    description:        "The Nilgai (Blue Bull) is the largest Asian antelope and is endemic to the Indian subcontinent. Males have a distinctive bluish-grey coat and a small tuft of hair on the throat. Nilgai are revered in parts of India because of their blue colour, associated with Lord Krishna.",
    habitat:            "Short grasslands, scrub forests, and agricultural areas",
    threats:            ["Hunting in some regions where considered crop pests", "Habitat conversion to farmland", "Road accidents"],
    funFacts:           ["Despite being antelopes, Nilgai are called 'Blue Bulls' for their blue-grey coat", "Males are much larger than females — almost twice the weight", "They are the only living member of genus Boselaphus", "Nilgai prefer walking to running; they can trot for long distances"],
    coordinates:        { lat: 26.0, lng: 80.0, locationName: "Uttar Pradesh Grasslands" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/8/87/Nilgai_in_Keoladeo_Ghana_National_Park.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/8/87/Nilgai_in_Keoladeo_Ghana_National_Park.jpg",
    ],
  },
  {
    name:               "Sloth Bear",
    scientificName:     "Melursus ursinus",
    type:               "Mammal",
    zone:               "Central India",
    ecosystem:          "Forest",
    population:         20000,
    habitatLoss:        50,
    pollutionLevel:     20,
    climateRisk:        35,
    conservationStatus: "Vulnerable",
    description:        "The Sloth Bear is a nocturnal insectivore bear native to the Indian subcontinent. It has a distinctive long lower lip and palate for sucking up insects, particularly termites and honey bee nests. Despite its name, it is not related to sloths but gets the name from its long claws.",
    habitat:            "Dry and moist deciduous forests, grasslands, and scrublands",
    threats:            ["Habitat loss and fragmentation", "Bile poaching for traditional medicine", "Road kills", "Human-bear conflict"],
    funFacts:           ["Sloth Bears can close their nostrils to keep insects out while digging", "They make a loud sucking sound when eating — the loudest of any mammal while feeding", "Mother sloth bears carry their cubs on their backs — unique among bears", "They can consume 10,000 termites in a single sitting"],
    coordinates:        { lat: 23.0, lng: 79.5, locationName: "Panna National Park, Madhya Pradesh" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/3/34/Sloth_bear_peshkar.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/3/34/Sloth_bear_peshkar.jpg",
    ],
  },
  {
    name:               "Indian Pangolin",
    scientificName:     "Manis crassicaudata",
    type:               "Mammal",
    zone:               "Central India",
    ecosystem:          "Forest",
    population:         5000,
    habitatLoss:        70,
    pollutionLevel:     20,
    climateRisk:        30,
    conservationStatus: "Endangered",
    description:        "The Indian Pangolin is the world's most trafficked mammal, hunted for its scales used in traditional medicine. This unique insectivore is covered in overlapping keratin scales — like a living pine cone. When threatened, it rolls into a tight ball, which unfortunately makes it easy to pick up by poachers.",
    habitat:            "Forests, grasslands, and degraded habitats with termite mounds",
    threats:            ["Massive illegal wildlife trade for scales and meat", "Habitat destruction", "Traditional medicine demand in China and Southeast Asia", "Road kills"],
    funFacts:           ["Pangolin scales are made of keratin — the same material as human fingernails", "They have no teeth and swallow stones to help grind food", "A pangolin can eat up to 70 million insects per year", "They have been around for 80 million years — older than many dinosaurs"],
    coordinates:        { lat: 20.5, lng: 78.0, locationName: "Central Indian Forests" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/2/29/Pangolin_2_%282292581717%29.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/2/29/Pangolin_2_%282292581717%29.jpg",
    ],
  },
  {
    name:               "Fishing Cat",
    scientificName:     "Prionailurus viverrinus",
    type:               "Mammal",
    zone:               "Wetlands",
    ecosystem:          "Wetland",
    population:         10000,
    habitatLoss:        60,
    pollutionLevel:     40,
    climateRisk:        45,
    conservationStatus: "Vulnerable",
    description:        "The Fishing Cat is a medium-sized wild cat adapted to life in and around water. Unlike most cats, it actively seeks out water and is an expert swimmer. Found in wetlands and mangroves of India, it is named for its remarkable ability to catch fish by scooping them out of water.",
    habitat:            "Wetlands, mangroves, marshes, lakes, and rivers",
    threats:            ["Rapid degradation of wetland habitats", "Conversion of wetlands to aquaculture", "Hunting by fishermen who see them as competition", "Pollution of water bodies"],
    funFacts:           ["Fishing cats have partially webbed front paws for swimming", "They dive underwater to catch fish and can swim long distances", "Unlike domestic cats, fishing cats do not avoid water — they actively seek it", "They use their short, thick tails as rudders when swimming"],
    coordinates:        { lat: 22.5, lng: 88.0, locationName: "Sundarbans, West Bengal" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/8/8e/Fishing_Cat_Tennoji.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/8/8e/Fishing_Cat_Tennoji.jpg",
    ],
  },
  {
    name:               "Barasingha",
    scientificName:     "Rucervus duvaucelii",
    type:               "Mammal",
    zone:               "Central India",
    ecosystem:          "Grassland",
    population:         4000,
    habitatLoss:        55,
    pollutionLevel:     20,
    climateRisk:        30,
    conservationStatus: "Vulnerable",
    description:        "The Barasingha (Swamp Deer) is named for its impressive antlers — 'barah singha' means 'twelve-antlered' in Hindi. Once found across North and Central India, this graceful deer almost went extinct due to hunting and habitat loss. Kanha National Park's conservation success saved the hard-ground subspecies.",
    habitat:            "Tall grasslands, swampy areas, and river floodplains",
    threats:            ["Habitat conversion to agriculture", "Competition with cattle for grassland", "Hunting pressure", "Flooding of grassland habitats"],
    funFacts:           ["Male barasingha have antlers with up to 20 tines (points)", "They are one of the few deer that graze as well as browse", "Kanha National Park's famous conservation programme saved this species from extinction", "They are strong swimmers and can cross rivers to escape predators"],
    coordinates:        { lat: 22.3, lng: 80.6, locationName: "Kanha National Park, Madhya Pradesh" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/9/93/An_Indian_hog_deer.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/9/93/An_Indian_hog_deer.jpg",
    ],
  },
  {
    name:               "Indian Wolf",
    scientificName:     "Canis lupus pallipes",
    type:               "Mammal",
    zone:               "Grasslands",
    ecosystem:          "Dry Grassland",
    population:         3000,
    habitatLoss:        60,
    pollutionLevel:     20,
    climateRisk:        40,
    conservationStatus: "Endangered",
    description:        "The Indian Wolf is one of the most endangered wolves in the world. Smaller and lighter-furred than its northern cousins, it has adapted to life in the hot, arid grasslands of peninsular India. Once widespread, it now survives in scattered packs across a few protected areas.",
    habitat:            "Semi-arid grasslands, scrublands, and open habitats of peninsular India",
    threats:            ["Habitat degradation and conversion to agriculture", "Killing by livestock herders", "Persecution as a livestock predator", "Inbreeding in small isolated populations"],
    funFacts:           ["Indian wolves have adapted to live without the thick winter fur of northern wolves", "They avoid dense forests, preferring open landscapes for hunting", "A pack typically has only 6–8 members — smaller than northern wolf packs", "Indian wolves are genetically distinct enough to potentially be a separate species"],
    coordinates:        { lat: 18.5, lng: 74.5, locationName: "Maharashtra Grasslands" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/5/5f/White_wolf.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/5/5f/White_wolf.jpg",
    ],
  },
  {
    name:               "Lion-tailed Macaque",
    scientificName:     "Macaca silenus",
    type:               "Mammal",
    zone:               "Western Ghats",
    ecosystem:          "Rainforest",
    population:         3000,
    habitatLoss:        65,
    pollutionLevel:     20,
    climateRisk:        50,
    conservationStatus: "Endangered",
    description:        "The Lion-tailed Macaque is one of the rarest and most threatened primates in the world. Endemic to the rainforests of the Western Ghats, it gets its name from its silver-white mane and lion-like tufted tail. It lives entirely in the forest canopy and almost never descends to the ground.",
    habitat:            "Primary tropical moist evergreen forests of the Western Ghats",
    threats:            ["Severe fragmentation of remaining forest patches", "Tea and coffee plantation expansion", "Road construction through forest corridors", "Electrocution on power lines"],
    funFacts:           ["Lion-tailed macaques almost never come down to the ground — they are true canopy dwellers", "They have cheek pouches to store food while foraging", "The mane makes them look much larger and more intimidating", "They are flagship species for Western Ghats biodiversity conservation"],
    coordinates:        { lat: 10.5, lng: 76.5, locationName: "Silent Valley National Park, Kerala" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/8/8c/Macaca_silenus_-_Buffalo_Zoo.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/8/8c/Macaca_silenus_-_Buffalo_Zoo.jpg",
    ],
  },
  {
    name:               "Himalayan Monal",
    scientificName:     "Lophophorus impejanus",
    type:               "Bird",
    zone:               "Himalayan",
    ecosystem:          "Mountain",
    population:         5000,
    habitatLoss:        40,
    pollutionLevel:     15,
    climateRisk:        45,
    conservationStatus: "Safe",
    description:        "The Himalayan Monal is arguably the most colourful bird in Asia. The male has iridescent plumage that glitters with metallic green, copper, purple, and red. It is the national bird of Nepal and the state bird of Uttarakhand and Himachal Pradesh in India.",
    habitat:            "Rocky slopes with open woodland and subalpine meadows at 2,400–4,500 m elevation",
    threats:            ["Hunting for plumage", "Climate change reducing high-altitude habitat", "Disturbance from tourism", "Habitat degradation from overgrazing"],
    funFacts:           ["The male Himalayan Monal has 9 different metallic colours on its plumage", "It is called 'Danfe' in Nepal, where it is the national bird", "Males use their strong beaks to dig into frozen ground to find tubers and insects", "The female is brown and cryptically coloured for camouflage on the nest"],
    coordinates:        { lat: 30.5, lng: 78.5, locationName: "Valley of Flowers, Uttarakhand" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/3/31/Lophophorus_impejanus_-British_Columbia%2C_Canada-8.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/3/31/Lophophorus_impejanus_-British_Columbia%2C_Canada-8.jpg",
    ],
  },
  {
    name:               "King Cobra",
    scientificName:     "Ophiophagus hannah",
    type:               "Reptile",
    zone:               "Western Ghats",
    ecosystem:          "Forest",
    population:         10000,
    habitatLoss:        45,
    pollutionLevel:     20,
    climateRisk:        35,
    conservationStatus: "Vulnerable",
    description:        "The King Cobra is the world's longest venomous snake, capable of reaching 5.85 metres. Despite its fearsome reputation, it is generally shy and avoids humans when possible. The King Cobra is unique among snakes for building a nest and guarding its eggs — a true sign of parental behaviour.",
    habitat:            "Dense highland forests, bamboo thickets near streams and rivers",
    threats:            ["Habitat destruction from deforestation", "Killing due to fear and misidentification", "Collection for snake charming and medicine", "Road kill"],
    funFacts:           ["King cobras are the only snakes that build nests for their eggs", "Their venom is potent enough to kill an elephant", "They can lift one-third of their body length off the ground while still moving forward", "King cobras primarily eat other snakes — Ophiophagus means 'snake eater'"],
    coordinates:        { lat: 11.5, lng: 75.5, locationName: "Wayanad Wildlife Sanctuary, Kerala" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/4/4f/King_Cobra_Bali.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/4/4f/King_Cobra_Bali.jpg",
    ],
  },
  {
    name:               "Indian Cobra",
    scientificName:     "Naja naja",
    type:               "Reptile",
    zone:               "Indo-Malayan",
    ecosystem:          "Forest",
    population:         100000,
    habitatLoss:        20,
    pollutionLevel:     15,
    climateRisk:        25,
    conservationStatus: "Safe",
    description:        "The Indian Cobra (spectacled cobra) is one of the 'Big Four' venomous snakes in India. Known for the distinctive spectacle marking on the back of its hood, it is deeply embedded in Indian culture, religion, and mythology. Despite its venom, it is also celebrated as the snake of Lord Shiva.",
    habitat:            "Human-modified landscapes, forest edges, rice paddy fields, and urban areas",
    threats:            ["Road kills", "Persecution by farmers", "Collection for snake shows", "Habitat degradation"],
    funFacts:           ["The spectacle pattern on the hood looks like a pair of glasses", "They spread a hood by extending their ribs when threatened", "Indian cobras are responsible for the most snakebite deaths in India", "Despite death toll, they help farmers by eating rats that damage crops"],
    coordinates:        { lat: 16.0, lng: 80.0, locationName: "Southern India" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/6/6f/Indian_cobra.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/6/6f/Indian_cobra.jpg",
    ],
  },
  {
    name:               "Gharial",
    scientificName:     "Gavialis gangeticus",
    type:               "Reptile",
    zone:               "Rivers",
    ecosystem:          "Freshwater",
    population:         900,
    habitatLoss:        80,
    pollutionLevel:     60,
    climateRisk:        50,
    conservationStatus: "Critically Endangered",
    description:        "The Gharial is one of the most critically endangered crocodilians in the world. Distinguished by its extremely long, thin snout (an adaptation for catching fish), it is found in the fast-flowing rivers of northern India. The male's distinctive bulbous growth on the snout tip is called a 'ghara'.",
    habitat:            "Tropical rivers with deep, fast-flowing sections and sandy banks for nesting",
    threats:            ["River pollution from industrial and agricultural runoff", "Fishing net entanglement", "Sand mining destroying nesting beaches", "Dams and irrigation barrages blocking movement"],
    funFacts:           ["Gharials cannot walk on land — they can only slide on their bellies", "The 'ghara' (bulb on male's nose) is used for bubbles and vocalisation during mating", "A gharial's jaw has 27–29 upper and 25–26 lower teeth — ideal for catching slippery fish", "Baby gharials communicate with their mother using a high-pitched 'umma-umma' call"],
    coordinates:        { lat: 26.0, lng: 82.0, locationName: "National Chambal Sanctuary, UP/MP" },
    imageUrl:           "https://upload.wikimedia.org/wikipedia/commons/2/23/Gavialis_gangeticus_2.jpg",
    images:             [
      "https://upload.wikimedia.org/wikipedia/commons/2/23/Gavialis_gangeticus_2.jpg",
    ],
  },
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ Connected to MongoDB for seeding...");

    await Species.deleteMany();
    console.log("🗑️  Cleared existing species data");

    const inserted = await Species.insertMany(speciesData);
    console.log(`✅ Seeded ${inserted.length} species with images, habitat, threats, and funFacts`);

    console.log("\n🌿 Database seeded successfully!");
    console.log("🖼️  All species now have Wikipedia Commons image URLs");

    // Display a summary
    inserted.forEach((s) =>
      console.log(`   • ${s.name.padEnd(25)} — ${s.conservationStatus}`)
    );

    process.exit(0);
  } catch (error) {
    console.error("❌ Seeding error:", error.message);
    process.exit(1);
  }
};

seedDatabase();